version: "3"

services:
  nginx: 
    build: ./nginx
    restart: on-failure
    ports:
      - 80:80
  service:
    image: jisack/node-service-cluster
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8000:8000