version: 2
jobs:
  build-and-push:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Docker build and push to hub
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            echo $DB_HOST | echo $DB_NAME | docker image build -t jisack/node-service-cluster --file Dockerfile .
            docker image build -t jisack/nginx-service-cluster ./nginx
            docker image push jisack/node-service-cluster
            docker image push jisack/nginx-service-cluster
            ssh-keyscan -H 3.0.180.218 >> ~/.ssh/known_hosts
            scp -rp deploy/* nginx/nginx.conf ubuntu@3.0.180.218:~
            ssh ubuntu@3.0.180.218 ./deploy.sh
workflows:
  version: 2
  build:
    jobs:
      - build-and-push
