version: "3.7"

services:
  nginx: 
    image: jisack/nginx-service-cluster
    ports:
      - 80:80
    deploy:
      mode: replicated
      placement:
        constraints: [node.role == manager]
  service:
    image: jisack/node-service-cluster
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    deploy:
      replicas: 4
      # restart_policy:
      #   condition: on-failure
      #   delay: 5s
      #   max_attempts: 3
      placement:
        constraints: [node.role == worker]
      update_config: 
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first