version: '3.7'
services:
  swarm-dashboard:
      image: charypar/swarm-dashboard
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      ports:
        - 9999:8080
      environment:
        PORT: 8080
      deploy:
        replicas: 1
        placement:
          constraints:
            - node.role == manager
  docker-slack:
    image: int128/slack-docker
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - webhook=https://hooks.slack.com/services/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
    deploy:
      mode: replicated
      placement:
        constraints: [node.role == manager]
  netdata:
    image: netdata/netdata
    ports:
      - 19999:19999
    restart: always
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./netdata/health_alarm_notify.conf:/etc/netdata/health_alarm_notify.conf
      # - ./netdata/alarm.conf:/etc/netdata/health.d/alarm.conf
      # - ./netdata/netdata.conf:/etc/netdata/netdata.conf
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: replicated
      placement:
        constraints: [node.role == manager]